# -*- coding: utf-8 -*-
"""FNUpdate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAs6TjnjLTN08v3Bf0qv06514kyjffLm
"""

!pip install transformers accelerate datasets "scikit-learn==1.6.1" pandas nltk --break-system-packages --upgrade -q


import transformers, sys
print("Transformers:", transformers.__version__)
print("Python:", sys.version)


from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
files.upload()

import os
os.listdir()

import pandas as pd
import re, nltk, torch
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords

nltk.download("stopwords")
stop_words = set(stopwords.words("english"))



def clean_text(text):
    text = str(text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9.,!? ]", "", text)
    text = text.lower()
    return " ".join(w for w in text.split() if w not in stop_words)

true_df = pd.read_csv("True.csv", on_bad_lines="skip").head(3500)
fake_df = pd.read_csv("Fake.csv", on_bad_lines="skip").head(3500)

true_df["label"] = 1
fake_df["label"] = 0

df = pd.concat([true_df, fake_df]).sample(frac=1).reset_index(drop=True)


df["text"] = (df["title"].fillna("") + " " + df["text"].fillna("")).apply(clean_text)
df = df.drop_duplicates(subset="text").reset_index(drop=True)

train_df, temp_df = train_test_split(df, test_size=0.2, stratify=df["label"], random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df["label"], random_state=42)


train_texts = train_df["text"].tolist()
train_labels = train_df["label"].tolist()

val_texts = val_df["text"].tolist()
val_labels = val_df["label"].tolist()

test_texts = test_df["text"].tolist()
test_labels = test_df["label"].tolist()

leak = set(train_texts).intersection(set(test_texts))
print("Leakage count:", len(leak))

import random

def augment(text):
    words = text.split()
    if len(words) > 5 and random.random() < 0.3:
        del words[random.randint(0, len(words)-1)]
    return " ".join(words)

train_texts = [augment(t) for t in train_texts]

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import accuracy_score, classification_report, roc_curve, auc
import matplotlib.pyplot as plt

tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))
X_train_tfidf = tfidf.fit_transform(train_df["text"])
X_test_tfidf  = tfidf.transform(test_df["text"])
y_train_bl    = train_df["label"].values
y_test_bl     = test_df["label"].values

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "SVM":                 LinearSVC(class_weight="balanced"),
    "Naive Bayes":         ComplementNB(),
}

plt.figure(figsize=(8, 6))

for name, clf in models.items():
    clf.fit(X_train_tfidf, y_train_bl)
    preds = clf.predict(X_test_tfidf)

    print(f"\n=== {name} ===")
    print(f"Accuracy: {round(accuracy_score(y_test_bl, preds)*100, 2)}%")
    print(classification_report(y_test_bl, preds, target_names=["Fake", "True"]))

    if hasattr(clf, "predict_proba"):
        scores = clf.predict_proba(X_test_tfidf)[:, 1]
    else:
        scores = clf.decision_function(X_test_tfidf)

    fpr, tpr, _ = roc_curve(y_test_bl, scores)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], "k--", label="Random")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve — Baseline Models")
plt.legend()
plt.tight_layout()
plt.show()

from transformers import AutoTokenizer, AutoConfig

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

train_enc = tokenizer(train_texts, truncation=True, padding=True)
val_enc = tokenizer(val_texts, truncation=True, padding=True)
test_enc = tokenizer(test_texts, truncation=True, padding=True)

import datasets

train_dataset = datasets.Dataset.from_dict({**train_enc, "labels": train_labels})
val_dataset = datasets.Dataset.from_dict({**val_enc, "labels": val_labels})
test_dataset = datasets.Dataset.from_dict({**test_enc, "labels": test_labels})

from transformers import AutoModelForSequenceClassification, DataCollatorWithPadding, Trainer, TrainingArguments

config = AutoConfig.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2,
    dropout=0.2,
    attention_dropout=0.2,
)
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", config=config)

data_collator = DataCollatorWithPadding(tokenizer)


use_fp16 = torch.cuda.is_available()

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    fp16=use_fp16,
)

from transformers import EarlyStoppingCallback

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

print("CUDA available:", torch.cuda.is_available())

trainer.train()
trainer.save_model("distilbert-fake-news")
tokenizer.save_pretrained("distilbert-fake-news")

from sklearn.metrics import accuracy_score, classification_report

preds = trainer.predict(test_dataset)
pred_labels = preds.predictions.argmax(-1)

print("Accuracy:", accuracy_score(test_labels, pred_labels))
print(classification_report(test_labels, pred_labels))


print("Remaining overlap:", set(train_texts).intersection(set(test_texts)))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

sample_raw = "Government confirms climate change is accelerating."

sample = clean_text(sample_raw)

inputs = tokenizer(sample, return_tensors="pt", truncation=True, padding=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)
    probs = torch.softmax(outputs.logits, dim=1)
    pred = probs.argmax(dim=1).item()
    conf = probs[0][pred].item()

print("Prediction:", "True News" if pred == 1 else "Fake News")
print("Confidence:", conf * 100)

from transformers import AutoModelForSequenceClassification
import torch
import datasets
from sklearn.metrics import accuracy_score

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
liar_model = AutoModelForSequenceClassification.from_pretrained("distilbert-fake-news").to(device)
liar_model.eval()


import pandas as pd


liar_train_df = pd.read_csv("train.tsv", sep="\t", header=None)
liar_val_df   = pd.read_csv("valid.tsv", sep="\t", header=None)
liar_test_df  = pd.read_csv("test.tsv", sep="\t", header=None)

label_map = {
    "true": 1,
    "mostly-true": 1,
    "half-true": 1,
    "barely-true": 0,
    "false": 0,
    "pants-fire": 0,
}

for df_ in [liar_train_df, liar_val_df, liar_test_df]:
    df_["label_bin"] = df_[1].map(label_map)

    df_["text"] = df_[2].apply(clean_text)


liar_texts = liar_test_df["text"].tolist()
liar_labels = liar_test_df["label_bin"].tolist()

liar_enc = tokenizer(liar_texts, truncation=True, padding=True, max_length=256)
liar_dataset = datasets.Dataset.from_dict({**liar_enc, "labels": liar_labels})


liar_trainer = Trainer(
    model=liar_model,
    processing_class=tokenizer,
    data_collator=data_collator,
)


preds = liar_trainer.predict(liar_dataset)
pred_labels = preds.predictions.argmax(-1)


print("LIAR Cross-domain Accuracy:", accuracy_score(liar_labels, pred_labels))

!pip install streamlit transformers torch pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import re
# import streamlit as st
# import torch
# from transformers import AutoTokenizer, AutoModelForSequenceClassification
# 
# st.set_page_config(page_title="Fake News Detection Bot", layout="centered")
# st.title("📰 Fake News Detection Chatbot")
# st.write("Paste a news article or snippet below and I will predict whether it is fake or real.")
# 
# STOP_WORDS = {
#     "a", "an", "the", "and", "or", "but", "if", "of", "at", "by", "for",
#     "with", "about", "against", "between", "into", "through", "during",
#     "before", "after", "above", "below", "to", "from", "up", "down", "in",
#     "out", "on", "off", "over", "under", "again", "further", "then", "once",
#     "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
#     "do", "does", "did", "this", "that", "these", "those", "it", "its",
# }
# 
# def clean_text(text):
#     text = str(text)
#     text = re.sub(r"http\S+", "", text)
#     text = re.sub(r"[^a-zA-Z0-9.,!? ]", "", text)
#     text = text.lower()
#     return " ".join(w for w in text.split() if w not in STOP_WORDS)
# 
# 
# @st.cache_resource
# def load_model():
#     MODEL_REPO = "RayOfLife/FakeBotV2"
# 
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_REPO)
#     model = AutoModelForSequenceClassification.from_pretrained(MODEL_REPO)
#     model.eval()
#     return tokenizer, model
# 
# 
# tokenizer, model = load_model()
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model = model.to(device)
# 
# user_input = st.text_area("Enter news text:", height=200)
# 
# if st.button("Analyze"):
#     if user_input.strip() == "":
#         st.warning("Please enter some text.")
#     else:
#         cleaned_input = clean_text(user_input)
#         inputs = tokenizer(cleaned_input, return_tensors="pt", truncation=True, padding=True, max_length=256)
#         inputs = {k: v.to(device) for k, v in inputs.items()}
#         with torch.no_grad():
#             outputs = model(**inputs)
#             probs = torch.softmax(outputs.logits, dim=1)
#             pred = probs.argmax(dim=1).item()
#             conf = probs[0][pred].item()
# 
#         label = "True News" if pred == 1 else "Fake News"
#         st.subheader("Result")
#         st.write(f"🧠 Prediction: **{label}**")
#         st.write(f"📊 Confidence: **{round(conf*100,2)}%**")
# 
# 
#
